parameters:
#    ss_fichier.example.class: Ss\FichierBundle\Example

services:
#    ss_fichier.example:
#        class: %ss_fichier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
